### ISSUE TITLE
Compatible with dagu, or possibility to make it compatible.

### ISSUE THREAD

**Issue by thd2020** [amazingfate/armbian-xiaomi-elish#4]
Hi, Mr. amazing fate:
I'm glad to see this armbian image on pad 5 pro (nabu). However, I've got a pad 5 pro 12.4 and it seemed not to work with this properly.
I followed the instructions given by readme file, and I've tried both csot and boe boot image.
I wonder for what reason this failed to work with dagu. Is it simply the boot.img not compatible? If so, how can I alter it to make it work? The processor is the same so I feel there shall not be problem. I think changing some params and configs of the boot image will bring it to work. But how?

Current Status:
## 1. When booting from these two (csot and boe) images a splash command line screen can be seen but only about one second, then blank screen( screen with LED on):
![2a84d70465af8af9f2b8386a84101bb](https://github.com/amazingfate/armbian-xiaomi-elish/assets/74453079/fa835cc4-e8a0-4023-93d0-da6e4389e29c)

**Comment by amazingfate** [comment]
elish and dagu have different panels so that's normal.
For the usb network, you may need manually install rndis driver for windows: https://learn.microsoft.com/fr-fr/windows-hardware/drivers/network/remote-ndis-inf-template#rndis-inf-template-for-ndis-60-windows-7-and-later
I don't use windows and usb network is  working out of box on linux.
